FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y curl tar git python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
ADD https://github.com/MrDave/StaticJinjaPlus/archive/main.tar.gz /tmp/app.tar.gz
RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz

RUN mkdir -p /app/build /app/templates

RUN cp -r /app/templates_example/* /app/templates/

RUN pip install -r /app/requirements.txt

WORKDIR /app

CMD ["sh", "-c", "echo 'Log start.' && python3 main.py -w"]