FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y curl tar && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD https://github.com/MrDave/StaticJinjaPlus/archive/main.tar.gz /tmp/app.tar.gz

RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz

RUN pip install -r /app/requirements.txt

RUN mkdir -p /app/build /app/templates

RUN cp -r /app/templates_example/* /app/templates/

CMD ["sh", "-c", "echo 'Log start.' && python main.py -w"]
